### PR TITLE
Add option to only vendor git dependencies

### PR DESCRIPTION
**Pull request by repi**
Added a new option `--only-git-deps` which will only vendor dependencies that point to a git repository, not the ordinary crates.io dependencies.

We had multiple use cases where we want to vendor dependencies that we have on private Git repositories which this nicely solves.

I'm not sure if this is the best name of the option, or if one should have some more flexibility here with what to vendor or not. Would be open to changing it

### CODE REVIEW

**Comment by alexcrichton** [comment]
Seems reasonable to me, thanks! Could a test be added for this as well?

**Comment by repi** [comment]
Thanks! And yes I'll add a test for it

**Comment by repi** [comment]
Test added! Sorry about the delay

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Pull request merged**
