### PR TITLE
Build source bundle including vendored dependencies

### LINKED ISSUE #50: Provide tarball with vendored sources
With https://github.com/rust-lang/cargo/pull/2857 being merged `cargo vendor` seems like a useful tool to  implement a fetch task for build systems like [Nix](https://nixos.org/nix/) or [Yocto](https://www.yoctoproject.org/).

However there seems to be a bootstraping issues. In order to fetch the dependencies of `cargo vendor` you already need `cargo vendor`.

One elegant solution would be to provide a source tarball that containes the `vendored-sources` directory of a release. This way `cargo vendor` could be built without needing the dependency fetch state and thus avoiding the bootstrap problem.

### PR DESCRIPTION
**Pull request by bachp**
This simplifies boostrapping as one can just download the bundle
including all dependencies.

Closes #50

### CODE REVIEW

**Comment by bachp** [comment]
Not sure how to test this

**Comment by bachp** [comment]
Ok I was able to test it: https://github.com/bachp/cargo-vendor/releases

**Comment by alexcrichton** [comment]
It looks like this creates a tarball for just the dependencies? Perhaps this could create a tarball for the source code itself?

**Comment by bachp** [comment]
@alexcrichton No it actually creates a tarball including the sources + a vendor folder.

- `git archive` is used to get a clean source tree
- the build `cargo vendor` binary is used to fetch the vendor directory which is then copied into the new tarball
- the resulting folder is then put into the tarball

**Comment by alexcrichton** [comment]
Could this just produce one tarball with all source code necessary? I feel like that's what a "standard source tarball" generally looks like...

**Comment by bachp** [comment]
@alexcrichton I'm not sure what you mean with "all source code necessary". The tarball contains the `cargo-vendor` source code as found on github plus the vendored depenencies in a `vendor` directory. You can have a look at my example [here](https://github.com/bachp/cargo-vendor/releases/download/0.1.12-test3/cargo-vendor-0.1.12-test3-src.deps.tar.gz).

Do you expect it to contain more? Or is there some more source code that I'm missing?

**Comment by alexcrichton** [comment]
Hm I think I may have read the wrong version of the patch... in any case sorry this looks great! Could the tarball be called `cargo-vendor-src-$TAG.tar.gz` perhaps?

**Comment by bachp** [comment]
Done

Example will appear [here](https://github.com/bachp/cargo-vendor/releases) once the build is complete

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
